version: '3.8'

services:
  go:
    container_name: go-service
    image: my-go-app
    ports:
      - "8080:8080"
    # Add any other configurations needed for your Go service

  nextjs:
    container_name: nextjs-service
    image: my-nextjs-app
    ports:
      - "3000:3000"
    # Add any other configurations needed for your Next.js service

  wordpress:
    container_name: wordpress-service
    image: my-wordpress-site:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ashu
      WORDPRESS_DB_PASSWORD: Inc42*
      WORDPRESS_DB_NAME: devops
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    container_name: db-service
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
