name: Next.js CI/CD

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .

      - name: Run Prettier
        run: npx prettier --check .

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

  deploy_staging:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Next.js Application
        run: npm run build

      - name: Deploy to Vercel
        run: vercel --prod
|
          
